environment:
  language: ruby
  language_versions:
    - jruby-1.7.8
  packages:
    - mongodb-2.2.3
    - java-1.7.0_05
    - memcached-1.4.5
    - mysql-5.1.56_percona_server
    - ruby-1.9.3_p194
  vars:
    PATH: /packages/encap/jruby-1.7.8/lib/jruby/bin:$PATH
    CORE: 8
    CUCUMBER_PROFILE: plain
    SPEC_OPTS: '"--order random --no-color"'

build:
  before:
    - gem install bundler
    - jruby -S bundle install --no-deployment
  run:
    - jruby -S bundle exec rspec spec
<% if( DOTCI_BRANCH =~ /deploy/ ) { %>
  after: export GEM_HOME=$WORKSPACE/tmp; mkdir -p $GEM_HOME; echo GEM_HOME is $GEM_HOME; gem install --no-ri --no-rdoc nokogiri jiraSOAP json google-api-client && ruby /home/builduser/bin/postbuild.rb --deploybot
<% } %>
