deployment_repo: git@github.groupondev.com:finance-engineering/spinderella.git
deployment_setup: bundle install --path .bundle
deployment_command: bundle exec cap torquebox:backbeat:staging deploy -S revision=GIT_SHA_TO_DEPLOY
