web:
  build: .
  command: bin/startup.sh
  ports:
    - 9292:9292
  environment:
    BACKBEAT_USER_ID: "9ab09c2f-68d5-4e0e-8844-3637eea44254"
    BACKBEAT_CLIENT_URL: "http://198.167.129.13:9090/api"
    RACK_ENV: docker
  links:
    - database
    - redis

workers:
  build: .
  command: bundle exec sidekiq -r app.rb -q accounting_backbeat_server_v2
  volumes:
    - .:/app
  links:
    - database
    - redis
  environment:
    RACK_ENV: docker

database:
  image: library/postgres:9.4
  environment:
    POSTGRES_USER: backbeat
    POSTGRES_PASSWORD: fed
    POSTGRES_DB: backbeat_docker

redis:
  image: library/redis
