common: &common
  reconnect: true
  template: template0
  encoding: unicode
  adapter: postgresql
  username: 'backbeat'
  password:
  pool: 200

development:
  <<: *common
  database: backbeat_dev

uat:
  <<: *common
  database: backbeat_uat
  hostname:
  url:
  password:

staging:
  <<: *common
  database: backbeat_staging
  hostname:
  url:
  password:

production:
  <<: *common
  database: backbeat_pg
  username: backbeat_prod_app
  url:
  password: yo_Bac7B34T_app_!

dba:
  <<: *common
  database: backbeat_pg
  username: backbeat_prod_dba
  url:
  password: yo_Bac7B34T_dba!

docker:
  reconnect: true
  adapter: postgresql
  username: backbeat
  password: fed
  database: backbeat_ci
  host: db
  schema_search_path: public
