common: &common
  reconnect: true
  adapter: mysql2
  username: root
  password:
  database: backbeat_dev

development:
  <<: *common
  database: backbeat_dev

uat:
  <<: *common
  database: backbeat_uat
  username: backbeat
  hostname: gds-snc1-backbeat-uat-rw-vip.snc1
  url: jdbc:mysql://gds-snc1-backbeat-uat-rw-vip.snc1/backbeat_uat
  password: Akk0unT!NgBakBeE8U$e6

staging:
  <<: *common
  database: backbeat_staging
  username: backbeat
  hostname: gds-snc1-backbeat-stg-rw-vip.snc1
  url: jdbc:mysql://gds-snc1-backbeat-stg-rw-vip.snc1/backbeat_staging
  password: Akk0unT!NgBakBeE8U$e6
