common: &common
  reconnect: true
  adapter: postgresql
  username: backbeat
  password: backbeat

development:
  <<: *common
  database: backbeat_dev

test:
  <<: *common
  database: backbeat_test

docker: &docker
  <<: *common
  reconnect: true
  adapter: postgresql
  username: backbeat
  password: backbeat
  database: backbeat_docker
  host: database
  schema_search_path: public

ci:
  <<: *docker
