development:
  reconnect: true
  template: template0
  encoding: unicode
  adapter: postgresql
  username: 'backbeat'
  password:
  pool: 200
  database: backbeat_dev

docker:
  reconnect: true
  adapter: postgresql
  username: backbeat
  password: fed
  database: backbeat_docker
  host: database
  schema_search_path: public
