development:
  sessions:
    default:
      database: workflow_dev
      hosts:
        - localhost:27017
      options:
        safe: true
  options:
    raise_not_found_error: false
    use_utc: true

test:
  sessions:
    default:
      database: workflow_test
      hosts:
        - localhost:27018
      options:
        safe: true
  options:
    raise_not_found_error: false
    use_utc: true

uat:
  sessions:
    default:
      database: workflow_uat
      hosts:
        - accounting-mongodb1-uat.snc1:27017
        - accounting-mongodb2-uat.snc1:27017
        - accounting-mongodb3-uat.snc1:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false
    use_utc: true

staging:
  sessions:
    default:
      database: workflow_staging
      hosts:
        - accounting-mongodb1-staging.snc1:27017
        - accounting-mongodb2-staging.snc1:27017
        - accounting-mongodb3-staging.snc1:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false
    use_utc: true

production:
  sessions:
    default:
      database: workflow_production
      hosts:
        - accounting-tokumx1.snc1:27017
        - accounting-tokumx2.snc1:27017
        - accounting-tokumx3.snc1:27017
      options:
        consistency: :strong
        max_retries: 10
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false
    use_utc: true
