development:
  sessions:
    default:
      database: workflow_dev
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: workflow_test
      hosts:
        - localhost:27018
  options:
    raise_not_found_error: false

uat:
  sessions:
    default:
      database: workflow_uat
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false

stage:
  sessions:
    default:
      database: workflow_stage
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: workflow_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false