development:
  sessions:
    default:
      database: workflow_dev
      hosts:
        - localhost:27017
      options:
        safe: true
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: workflow_test
      hosts:
        - localhost:27018
      options:
        safe: true
  options:
    raise_not_found_error: false

uat:
  sessions:
    default:
      database: workflow_uat
      hosts:
        - accounting-utility1-uat.snc1:27018
        - accounting-utility1-staging.snc1:27018
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: workflow_stage
      hosts:
        - accounting-utility1-staging.snc1:27017
        - accounting-utility1-uat.snc1:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: workflow_production
      hosts:
        - accounting-mongodb1.snc1:27017
        - accounting-mongodb2.snc1:27017
        - accounting-mongodb3.snc1:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
        safe: true
  options:
    raise_not_found_error: false
