development:
  sessions:
    default:
      database: workflow_dev
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: workflow_test
      hosts:
        - localhost:27018
  options:
    raise_not_found_error: false

uat:
  sessions:
    replica_set:
      # This configuration is a 3 node replica set.
      hosts:
        - accounting-utility1-uat.snc1:27018
        - accounting-utility1-staging.snc1:27018
      options:
        consistency: :eventual
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: workflow_stage
      hosts:
        - localhost:27017
      options:
        consistency: :eventual
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: workflow_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 5
        retry_interval: 1
  options:
    raise_not_found_error: false