test:
  log: /tmp/backbeat.log
  log_level: DEBUG
  log_format: json
  dashboard_auth_token: '6dy6L8v8942jrbV622dr'
  dashboard_base_uri:   'http://localhost:3030/widgets/'
  queue: '/queues/accounting_backbeat_internal'

development:
  log: /tmp/backbeat.log
  log_level: DEBUG
  log_format: json
  dashboard_auth_token: '6dy6L8v8942jrbV622dr'
  dashboard_base_uri:   'http://localhost:3030/widgets/'

uat:
  log: /var/groupon/backbeat/shared/log/backbeat.log
  log_level: INFO
  log_format: json
  dashboard_auth_token: '6dy6L8v8942jrbV622dr'
  dashboard_base_uri:   'http://localhost:3030/widgets/'

staging:
  log: /var/groupon/backbeat/shared/log/backbeat.log
  log_level: INFO
  log_format: json
  dashboard_auth_token: '6dy6L8v8942jrbV622dr'
  dashboard_base_uri:   'http://localhost:3030/widgets/'

production:
  log: /var/groupon/backbeat/shared/log/backbeat.log
  log_level: INFO
  log_format: json
  dashboard_auth_token: '6dy6L8v8942jrbV622dr'
  dashboard_base_uri:   'http://localhost:3030/widgets/'

squash:
  api_key:        '9af7f0de-ddb0-4db3-9285-6b93d1dcb743'
  api_host:       'https://squash.groupondev.com'
  revision_file:  'REVISION'
