default: &default
  log_level: DEBUG
  log_format: json
  async_queue: 'accounting_backbeat_server'
  log: /var/groupon/backbeat/shared/log/backbeat.log

test:
  <<: *default
  log: /tmp/backbeat.log

development:
  <<: *default
  log: /tmp/backbeat.log

uat:
  <<: *default
  log_level: INFO

staging:
  <<: *default
  log_level: INFO

production:
  <<: *default
  log_level: INFO

squash:
  api_key:        'cb3078c0-ef99-4ec2-8bfe-2716226a4a7c'
  api_host:       'http://accounting-squash1.snc1:5000/'
  revision_file:  'REVISION'
