common: &common
  host: localhost
  port: 6379

development:
  <<: *common
  namespace: backbeat_development

test:
  <<: *common
  namespace: backbeat_test

docker: &docker
  host: redis
  port: 6379

ci:
  <<: *docker
