defaults: &defaults
  namespace: backbeat
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

docker: &docker
  namespace: backbeat
  host: redis
  port: 6379

uat:
  <<: *docker

staging:
  <<: *docker

production:
  <<: *docker

