defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

uat:
  host: newuat-redis-vip
  port: 6379

staging:
  host: general-redis-staging-vip
  port: 6379

production:
  host: general-redis-vip
  port: 6379

docker:
  host: redis
