defaults:
  log_level: INFO
  async_queue: backbeat_server
  log: ~
  client_timeout: 172800
  alerts:
    email_to: sample@email.com
    email_from: alerts-sample@email.com
  schedules:
    heal_nodes: '0 */2 * * * *'
    daily_activity: '0 12 * * * *'
    log_queues: '0 */5 * * * *'
