defaults:
  log_level: INFO
  async_queue: backbeat_server
  log: ~
  client_timeout: 172800
  alerts:
    email_to: sample@email.com
    email_from: alerts-sample@email.com
  job_frequency:
    heal_nodes: 7200
